use_frameworks!

platform :ios, '10.0'

target 'ImgBlurLibrary_Example' do
  pod 'ImgBlurLibrary', :path => '../'

  target 'ImgBlurLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
